export const NAV_ACTIVATE = "NAV_ACTIVATE";

export const USER_ROLES = {
  ROLE_ADMIN: "ADMIN",
  ROLE_STORE: "STORE",
  ROLE_PURCHASE: "PURCHASE",
  ROLE_USER: "USER"
};

export const MISC_CONSTANTS = {
  STORE_INITIALIZED: 'STORE_INITIALIZED'
};

export const USER_CONSTANTS = {
  INITIALIZE_USER: 'INITIALIZE_USER',
  USER_AUTH_PROGRESS: 'USER_AUTH_PROGRESS',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAIL: 'USER_AUTH_FAIL',
  USER_ADD_FORM_TOGGLE: 'USER_ADD_FORM_TOGGLE',
  USER_ADD_SUCCESS: 'USER_ADD_SUCCESS',
  USER_ADD_FAIL: 'USER_ADD_FAIL',
  USER_EDIT_FORM_TOGGLE: 'USER_EDIT_FORM_TOGGLE',
  USER_EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
  USER_EDIT_FAIL: 'USER_EDIT_FAIL',
  // USER_REMOVE_PROGRESS: 'USER_REMOVE_PROGRESS',
  USER_REMOVE_SUCCESS: 'USER_REMOVE_SUCCESS',
  USER_REMOVE_FAIL: 'USER_REMOVE_FAIL',
  USER_BAD_REQUEST: 'USER_BAD_REQUEST'
};

export const CATEGORY_CONSTANTS = {
  INITIALIZE_CATEGORY: 'INITIALIZE_CATEGORY',
  CATEGORY_BAD_REQUEST: 'CATEGORY_BAD_REQUEST',
  CATEGORY_ADD_FORM_TOGGLE: 'CATEGORY_ADD_FORM_TOGGLE',
  CATEGORY_ADD_PROGRESS: 'CATEGORY_ADD_PROGRESS',
  CATEGORY_ADD_SUCCESS: 'CATEGORY_ADD_SUCCESS',
  CATEGORY_ADD_FAIL: 'CATEGORY_ADD_FAIL',
  CATEGORY_EDIT_FORM_TOGGLE: 'CATEGORY_EDIT_FORM_TOGGLE',
  CATEGORY_EDIT_PROGRESS: 'CATEGORY_EDIT_PROGRESS',
  CATEGORY_EDIT_SUCCESS: 'CATEGORY_EDIT_SUCCESS',
  CATEGORY_EDIT_FAIL: 'CATEGORY_EDIT_FAIL',
  CATEGORY_REMOVE_SUCCESS: 'CATEGORY_REMOVE_SUCCESS',
  CATEGORY_REMOVE_FAIL: 'CATEGORY_REMOVE_FAIL',
  CATEGORY_FILTER: 'CATEGORY_FILTER',
  CATEGORY_SORT: 'CATEGORY_SORT'
};

export const SUB_CATEGORY_CONSTANTS = {
  SUB_CATEGORY_BAD_REQUEST: 'SUB_CATEGORY_BAD_REQUEST',
  SUB_CATEGORY_ADD_FORM_TOGGLE: 'SUB_CATEGORY_ADD_FORM_TOGGLE',
  SUB_CATEGORY_ADD_PROGRESS: 'SUB_CATEGORY_ADD_PROGRESS',
  SUB_CATEGORY_ADD_SUCCESS: 'SUB_CATEGORY_ADD_SUCCESS',
  SUB_CATEGORY_ADD_FAIL: 'SUB_CATEGORY_ADD_FAIL',
  SUB_CATEGORY_EDIT_FORM_TOGGLE: 'SUB_CATEGORY_EDIT_FORM_TOGGLE',
  SUB_CATEGORY_EDIT_PROGRESS: 'SUB_CATEGORY_EDIT_PROGRESS',
  SUB_CATEGORY_EDIT_SUCCESS: 'SUB_CATEGORY_EDIT_SUCCESS',
  SUB_CATEGORY_EDIT_FAIL: 'SUB_CATEGORY_EDIT_FAIL',
  SUB_CATEGORY_REMOVE_SUCCESS: 'SUB_CATEGORY_REMOVE_SUCCESS',
  SUB_CATEGORY_REMOVE_FAIL: 'SUB_CATEGORY_REMOVE_FAIL'

};

export const SECTION_CONSTANTS = {
  INITIALIZE_SECTION: 'INITIALIZE_SECTION',
  SECTION_BAD_REQUEST: 'SECTION_BAD_REQUEST',
  SECTION_ADD_FORM_TOGGLE: 'SECTION_ADD_FORM_TOGGLE',
  SECTION_ADD_PROGRESS: 'SECTION_ADD_PROGRESS',  
  SECTION_ADD_SUCCESS: 'SECTION_ADD_SUCCESS',
  SECTION_ADD_FAIL: 'SECTION_ADD_FAIL',
  SECTION_EDIT_FORM_TOGGLE: 'SECTION_EDIT_FORM_TOGGLE',
  SECTION_EDIT_PROGRESS: 'SECTION_EDIT_PROGRESS', 
  SECTION_EDIT_SUCCESS: 'SECTION_EDIT_SUCCESS',
  SECTION_EDIT_FAIL: 'SECTION_EDIT_FAIL',
  SECTION_REMOVE_SUCCESS: 'SECTION_REMOVE_SUCCESS',
  SECTION_REMOVE_FAIL: 'SECTION_REMOVE_FAIL'
};

export const SUPPLIER_CONSTANTS = {
  INITIALIZE_SUPPLIER: 'INITIALIZE_SUPPLIER',
  SUPPLIER_BAD_REQUEST: 'SUPPLIER_BAD_REQUEST',
  SUPPLIER_ADD_FORM_TOGGLE: 'SUPPLIER_ADD_FORM_TOGGLE',
  SUPPLIER_ADD_PROGRESS: 'SUPPLIER_ADD_PROGRESS',
  SUPPLIER_ADD_SUCCESS: 'SUPPLIER_ADD_SUCCESS',
  SUPPLIER_ADD_FAIL: 'SUPPLIER_ADD_FAIL',
  SUPPLIER_EDIT_FORM_TOGGLE: 'SUPPLIER_EDIT_FORM_TOGGLE',
  SUPPLIER_EDIT_PROGRESS: 'SUPPLIER_EDIT_PROGRESS',
  SUPPLIER_EDIT_SUCCESS: 'SUPPLIER_EDIT_SUCCESS',
  SUPPLIER_EDIT_FAIL: 'SUPPLIER_EDIT_FAIL',
  SUPPLIER_REMOVE_SUCCESS: 'SUPPLIER_REMOVE_SUCCESS',
  SUPPLIER_REMOVE_FAIL: 'SUPPLIER_REMOVE_FAIL',

  SUPPLIER_FILTER: 'SUPPLIER_FILTER',
  SUPPLIER_SORT: 'SUPPLIER_SORT'
};

export const PRODUCT_CONSTANTS = {
  // PRODUCT_FETCH_PROGRESS: 'PRODUCT_FETCH_PROGRESS',
  // PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
  // PRODUCT_FETCH_FAIL: 'PRODUCT_FETCH_FAIL',
  PRODUCT_ADD_FORM_TOGGLE: 'PRODUCT_ADD_FORM_TOGGLE',
  PRODUCT_ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
  PRODUCT_ADD_FAIL: 'PRODUCT_ADD_FAIL',
  PRODUCT_SYNC_PROGRESS: 'PRODUCT_SYNC_PROGRESS',
  PRODUCT_SYNC_SUCCESS: 'PRODUCT_SYNC_SUCCESS',
  PRODUCT_UPLOAD_PROGRESS: 'PRODUCT_UPLOAD_PROGRESS',
  PRODUCT_UPLOAD_FORM_TOGGLE: 'PRODUCT_UPLOAD_FORM_TOGGLE',
  PRODUCT_UPLOAD_SUCCESS: 'PRODUCT_UPLOAD_SUCCESS',
  PRODUCT_UPLAOD_ERROR: 'PRODUCT_UPLAOD_ERROR',
  PRODUCT_UPLAOD_FAIL: 'PRODUCT_UPLAOD_FAIL',
  PRODUCT_EDIT_FORM_TOGGLE: 'PRODUCT_EDIT_FORM_TOGGLE',
  PRODUCT_EDIT_SUCCESS: 'PRODUCT_EDIT_SUCCESS',
  PRODUCT_EDIT_FAIL: 'PRODUCT_EDIT_FAIL',
  // PRODUCT_REMOVE_PROGRESS: 'PRODUCT_REMOVE_PROGRESS',
  PRODUCT_REMOVE_SUCCESS: 'PRODUCT_REMOVE_SUCCESS',
  PRODUCT_REMOVE_FAIL: 'PRODUCT_REMOVE_FAIL',
  PRODUCT_BAD_REQUEST: 'PRODUCT_BAD_REQUEST',
  PRODUCT_FILTER: 'PRODUCT_FILTER',
  PRODUCT_SORT: 'PRODUCT_SORT'
};

export const INVENTORY_CONSTANTS = {
  INITIALIZE_INVENTORY: 'INITIALIZE_INVENTORY',
  INVENTORY_EDIT_PROGRESS: 'INVENTORY_EDIT_PROGRESS',
  INVENTORY_EDIT_SUCCESS: 'INVENTORY_EDIT_SUCCESS',
  INVENTORY_EDIT_FAIL: 'INVENTORY_EDIT_FAIL'
};
